# Generated by Django 6.0.2 on 2026-02-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.FileField(upload_to='relatorios/')),
                ('estado', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='candidaturas.candidatura')),
            ],
        ),
    ]
