# Generated by Django 6.0.2 on 2026-06-25 16:19

import relatorios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatorios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='ficheiro',
            field=models.FileField(upload_to=relatorios.models.upload_relatorio_path),
        ),
    ]
