# Generated by Django 6.0.2 on 2026-04-16 19:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidaturas', '0004_alter_candidatura_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessoEstagio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_nome', models.CharField(blank=True, max_length=150)),
                ('supervisor_email', models.EmailField(blank=True, max_length=254)),
                ('supervisor_telefone', models.CharField(blank=True, max_length=30)),
                ('supervisor_cargo', models.CharField(blank=True, max_length=120)),
                ('local_estagio', models.CharField(blank=True, max_length=200)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('acordo_estagio', models.FileField(blank=True, null=True, upload_to='acordos_estagio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('estado', models.CharField(choices=[('PREPARACAO', 'Preparação'), ('EM_CURSO', 'Em curso'), ('EM_AVALIACAO', 'Em avaliação'), ('CONCLUIDO', 'Concluído')], default='PREPARACAO', max_length=30)),
                ('empresa_confirmada', models.BooleanField(default=False)),
                ('validado_servicos_academicos', models.BooleanField(default=False)),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('nota_publicada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processo', to='candidaturas.candidatura')),
                ('orientador', models.ForeignKey(blank=True, limit_choices_to={'role': 'ORIENTADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_orientados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
