# Generated by Django 6.0.2 on 2026-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario_orientador', models.TextField(blank=True)),
                ('comentario_empresa', models.TextField(blank=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
