# Generated by Django 6.0.2 on 2026-02-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avaliacoes', '0001_initial'),
        ('candidaturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='candidatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='candidaturas.candidatura'),
        ),
    ]
