# Generated by Django 6.0.2 on 2026-04-28 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
        ('processos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEntidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_nome_snapshot', models.CharField(max_length=150)),
                ('nota_pratica', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentario', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_entidade', to='processos.processoestagio')),
                ('submetida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_entidade_submetidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='AvaliacaoOrientador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_teorica', models.DecimalField(decimal_places=2, max_digits=4)),
                ('comentario', models.TextField(blank=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('orientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_orientador', to=settings.AUTH_USER_MODEL)),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_orientador', to='processos.processoestagio')),
            ],
            options={
                'ordering': ['-criada_em'],
            },
        ),
        migrations.DeleteModel(
            name='Avaliacao',
        ),
    ]
