# Generated by Django 6.0.2 on 2026-03-12 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidaturas', '0002_candidatura_aluno_candidatura_cv_candidatura_estagio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('candidatura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificado', to='candidaturas.candidatura')),
                ('orientador', models.ForeignKey(limit_choices_to={'role': 'ORIENTADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificados_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
