# Generated by Django 6.0.2 on 2026-03-25 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='orientador',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ORIENTADOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_orientados', to=settings.AUTH_USER_MODEL),
        ),
    ]
