# Generated by Django 6.0.2 on 2026-04-29 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0002_perfil_orientador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='orientador',
        ),
    ]
