# Generated by Django 6.0.2 on 2026-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITE', 'Aceite'), ('REJEITADO', 'Rejeitado')], default='PENDENTE', max_length=20)),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
