# Generated by Django 6.0.2 on 2026-03-12 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0001_initial'),
        ('estagios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='aluno',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'ALUNO'}, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidatura',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='CV em PDF'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='estagio',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='estagios.estagio'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='candidatura',
            unique_together={('aluno', 'estagio')},
        ),
    ]
