# Generated by Django 6.0.2 on 2026-03-12 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0002_candidatura_aluno_candidatura_cv_candidatura_estagio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatura',
            name='certificado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificado em PDF'),
        ),
    ]
