# Generated by Django 6.0.2 on 2026-04-16 19:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidaturas', '0003_candidatura_certificado_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatura',
            options={'ordering': ['-data_candidatura']},
        ),
        migrations.RemoveField(
            model_name='candidatura',
            name='certificado_pdf',
        ),
        migrations.AddField(
            model_name='candidatura',
            name='comprovativo_frequencia',
            field=models.FileField(blank=True, null=True, upload_to='candidaturas/comprovativos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='candidaturas/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('SUBMETIDA', 'Submetida'), ('ACEITE', 'Aceite'), ('REJEITADA', 'Rejeitada')], default='SUBMETIDA', max_length=20),
        ),
    ]
