# Generated by Django 6.0.2 on 2026-06-27 22:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estagio',
            name='duracao_meses',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
