# Generated by Django 6.0.2 on 2026-02-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('area', models.CharField(blank=True, max_length=120)),
                ('contacto', models.CharField(blank=True, max_length=120)),
                ('morada', models.CharField(blank=True, max_length=200)),
                ('nif', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
